"""make Tweet Model

Revision ID: 902a0505becb
Revises: e34a1f94c1d0
Create Date: 2022-11-24 20:18:51.447934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902a0505becb'
down_revision = 'e34a1f94c1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###
