"""add follower model

Revision ID: 915ca44d0ecd
Revises: 902a0505becb
Create Date: 2022-11-24 22:01:29.051724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915ca44d0ecd'
down_revision = '902a0505becb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
