"""add joinDate to user

Revision ID: e34a1f94c1d0
Revises: f8be30cb3e62
Create Date: 2022-11-24 19:52:46.338273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34a1f94c1d0'
down_revision = 'f8be30cb3e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joinDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('joinDate')

    # ### end Alembic commands ###
